### ISSUE TITLE
Config should be able to read all the possible cmd line options

### ISSUE THREAD

**Issue by MichalBryxi** [bertdeblock/gember#37]
As a user of gember, I'm now using following command to generate what I want within my project:

```sh
pnpm gember component --typescript --path=app/components --class-based logo
```

I would love to have to provide _minimum_ arguments as pretty much everything is always the same. In my mind default arguments should be stored in gember config file so that I can commit it and everyone can use those defaults without thinking.

Namely following arguments:
- `--typescript`
- `--path`
- `--class-based`

**Comment by bertdeblock** [comment]
Yes indeed, I was already working on supporting all CLI options in the config file. Will try to finish it asap.
